version: "3"
services:
  kfk-conn:
    image: zenoss/zing-kafkaconnect:0.1.0
    build: .
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kfk:9092
      CONNECT_GROUP_ID: databus-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _databus-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _databus-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _databus-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: kfk-sr:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: kfk-sr:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: kfk-conn
